### ISSUE TITLE
implicit none missing in example

### ISSUE THREAD

**Issue by ivan-pi** [alexeedm/pytorch-fortran#2]
https://github.com/alexeedm/pytorch-fortran/blob/cd4334a0f1bfbd87402a2dd1fa43f41c2a1cd150/examples/resnet_forward/resnet_forward.f90#L22

The example program uses implicit typing. It might lead to some surprises if someone tries to extend the example without noticing.

**Comment by alexeedm** [comment]
Thanks @ivan-pi for pointing it out, will fix that soon
