### ISSUE TITLE
Citing pytorch-fortran

### ISSUE THREAD

**Issue by pikarpov-LANL** [alexeedm/pytorch-fortran#3]
Hi Dmitry,

I am a Ph.D. student at UC Santa Cruz and Los Alamos National Laboratory. I specialize in ML-based turbulence modeling within stellar explosions. This repo has been incredibly helpful for the last chapter of my thesis, which involved the integration of PyTorch models in a legacy Fortran code for 1D supernovae ([pikarpov-lanl/COLLAPSO1D](https://github.com/pikarpov-LANL/COLLAPSO1D)). We are writing a paper for Astrophysical Journal on this subject, and I would like to give you proper credit for the pytorch-fortran repo. Do you have any preferences on how to cite your work?

In addition, I wrote an interface to integrate your ML wrapper into any legacy F90 code, which is pretty generalizable. As such, I think it would be highly beneficial for the astrophysical community if this pipeline would be published separately, e.g., in the Journal of Open Source Software. Please let me know your thoughts and whether you would want to collaborate. Feel free to send me an email (plkarpov@ucsc.edu).

**Comment by alexeedm** [comment]
Hey Platon, I'm glad you found this project helpful!
I've just created a Zenodo entry for the code: https://zenodo.org/record/7304774
This should give you a DOI to cite the code, hope this works for you.

Regarding the publication: I'm not sure this code deserves a full-fledged publication, it's not really a rocket science :) But I'm open for discussion here
