### ISSUE TITLE
failed to build gnu target

### ISSUE THREAD

**Issue by hwdef** [alexeedm/pytorch-fortran#5]
step:
1. cd `container`
2. python container.py gnu --pytorch-tag 1.13.1-cuda11.6-cudnn8-devel
3. docker build -t pytorch-fortran:v1.13.1-devel .
4. docker run --name pytorch-fortran -d  pytorch-fortran:v1.13.1-devel sleep 1000000
5. docker exec -it pytorch-fortran bash
6. apt update -y && apt install git -y
7. git clone https://github.com/alexeedm/pytorch-fortran.git
8. cd pytorch-fortran
9. ./make_gnu.sh

result
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/13084946/220288830-ee19cb8a-b0ae-404f-b20c-7d355dc7887e.png">

Did I do something wrong? I can't successfully run make_gnu.sh script as prompted in README.md

**Comment by ch21d012** [comment]
you have to add word target :: value in torch_ftn.f90 file in line 1842,1849,1856,1863

**Comment by hwdef** [comment]
> you have to add word target :: value in torch_ftn.f90 file in line 1842,1849,1856,1863

Thanks for your replay, I will try this.

**Comment by alexeedm** [comment]
Thanks for letting me know, I'll double-check and fix this

**Comment by alexeedm** [comment]
Fixed with 64d9aedbd739040f710512b9c5ae05b4828a5d05
